#!/usr/bin/perl -w

use strict;

use FindBin;
use lib "$FindBin::Bin/../lib";

use DateTime;
use File::Util;
use File::Copy qw/copy move/;
use File::Basename;
use File::Path qw/make_path/;

use NonameTV;
use NonameTV::DataStore;
use NonameTV::Config qw/ReadConfig/;
use NonameTV::Log qw/progress error d p w f/;

use Getopt::Long;

my $opt = { 'verbose' => 0 };

my $res = GetOptions( $opt, qw/verbose/ );

NonameTV::Log::SetVerbosity( $opt->{verbose} );

# Read configuration
my $conf = ReadConfig();
my $ds = NonameTV::DataStore->new( $conf->{DataStore} );
my $filestore = $conf->{FileStore};

# list files inside of the channel directory and check when they have been touched
  opendir(DIR, "/content/ftp/svt/");
  foreach my $cff (readdir(DIR))
  {
    if($cff =~ /^\./) { next; }
    my $org_cff = $cff;
    $cff =~ s/SVT_public_schedule_//g if $cff;

    my ( $id, $date, $enddate ) = split(/_/, $cff);

    my $cftype = join(',', File::Util->file_type( "/content/ftp/svt/$cff" ) );
    my $fsftype = join(',', File::Util->file_type( "/content/ftp/svt/$cff" ) );

    make_path(dirname("$filestore/svt1.svt.se/$org_cff"));
    move( "/content/ftp/svt/$org_cff", "$filestore/svt1.svt.se/$org_cff" );
    print "$cff moved to svt1.svt.se\n";

  }

exit;
