#!/bin/sh

# NONAMETV=nonametv-import
NONAMETV="tools/nonametv-import"

$NONAMETV Axess $1 $2 $3
$NONAMETV Arte $1 $2 $3
$NONAMETV BBCWorld $1 $2 $3
$NONAMETV Bleb $1 $2 $3
$NONAMETV CMore $1 $2 $3
$NONAMETV CMoreDK $1 $2 $3
$NONAMETV CMoreNO $1 $2 $3
$NONAMETV CMoreFI $1 $2 $3
$NONAMETV Discovery_xml $1 $2 $3
$NONAMETV Discovery_xmltv $1 $2 $3
$NONAMETV DR $1 $2 $3
$NONAMETV DR_radio $1 $2 $3
$NONAMETV DK4 $1 $2 $3
$NONAMETV DigiTV $1 $2 $3
$NONAMETV DreiSat $1 $2 $3
$NONAMETV DasErste $1 $2 $3
$NONAMETV Eurosport $1 $2 $3
$NONAMETV EurosportNO $1 $2 $3
$NONAMETV EurosportDK $1 $2 $3
$NONAMETV EurosportDE $1 $2 $3
$NONAMETV EurosportFI $1 $2 $3
$NONAMETV EBS $1 $2 $3
$NONAMETV Frikanalen $1 $2 $3
$NONAMETV Infomedia $1 $2 $3
$NONAMETV HBOHR $1 $2 $3
$NONAMETV HBOSI $1 $2 $3
$NONAMETV HBONordic $1 $2 $3
$NONAMETV Kanal23 $1 $2 $3
$NONAMETV KanalGlobal $1 $2 $3
$NONAMETV MTVde $1 $2 $3 # vg media license/foreign channels
$NONAMETV MTV_novg $1 $2 $3 # no vg media license
$NONAMETV Mtve $1 $2 $3
$NONAMETV MTGRadio $1 $2 $3
#$NONAMETV MTGRadioNO $1 $2 $3
$NONAMETV NRK $1 $2 $3
$NONAMETV ORF $1 $2 $3
$NONAMETV OKV $1 $2 $3
$NONAMETV OUTTV_web $1 $2 $3
$NONAMETV RadioSeven $1 $2 $3
$NONAMETV RBBDE $1 $2 $3
$NONAMETV RAI $1 $2 $3
$NONAMETV SBSRadio $1 $2 $3
$NONAMETV SBSTV $1 $2 $3
$NONAMETV SBSEurosport $1 $2 $3
$NONAMETV SRF $1 $2 $3
$NONAMETV SverigesRadio $1 $2 $3
$NONAMETV Viasat $1 $2 $3
$NONAMETV ViasatDK $1 $2 $3
$NONAMETV ViasatNO $1 $2 $3
$NONAMETV ViasatFI $1 $2 $3
$NONAMETV TV2 $1 $2 $3
$NONAMETV TV2Reg $1 $2 $3
$NONAMETV TV4 $1 $2 $3
$NONAMETV TV7 $1 $2 $3
$NONAMETV TVP $1 $2 $3
$NONAMETV TVNorge $1 $2 $3
$NONAMETV ZDF $1 $2 $3
$NONAMETV HRT $1 $2 $3
$NONAMETV ViasatPL $1 $2 $3
$NONAMETV EurosportPL $1 $2 $3
$NONAMETV KBSWorld $1 $2 $3
$NONAMETV Horse1 $1 $2 $3
$NONAMETV RTLDE $1 $2 $3
$NONAMETV KiKA $1 $2 $3
$NONAMETV Anixe $1 $2 $3
$NONAMETV RTS $1 $2 $3
$NONAMETV Arirang $1 $2 $3

# Download files
wget -O /home/jnylen/content/channels/tv_grab/ok54.xml http://epg.ok-rlp.de/xmltv/trier.xml
wget -O /home/jnylen/content/channels/tv_grab/nahetv.xml http://epg.ok-rlp.de/xmltv/idar-oberstein.xml
wget -O /home/jnylen/content/channels/tv_grab/okkl.xml http://epg.ok-rlp.de/xmltv/kaiserslautern.xml
wget -O /home/jnylen/content/channels/tv_grab/ok4.xml http://epg.ok-rlp.de/xmltv/koblenz.xml
wget -O /home/jnylen/content/channels/tv_grab/oklu.xml http://epg.ok-rlp.de/xmltv/ludwigshafen.xml
wget -O /home/jnylen/content/channels/tv_grab/okmainz.xml http://epg.ok-rlp.de/xmltv/mainz.xml
wget -O /home/jnylen/content/channels/tv_grab/okneustadt.xml http://epg.ok-rlp.de/xmltv/neustadt.xml
wget -O /home/jnylen/content/channels/tv_grab/oksp.xml http://epg.ok-rlp.de/xmltv/rodalben.xml
wget -O /home/jnylen/content/channels/tv_grab/okspeyer.xml http://epg.ok-rlp.de/xmltv/speyer.xml
wget -O /home/jnylen/content/channels/tv_grab/worms.xml http://epg.ok-rlp.de/xmltv/worms.xml
$NONAMETV TVGrabXX $1 $2 $3
