#!/bin/sh

NROOT=/home/jnylen/content
SC_OPT=-qq
V=false

if [ $1z = '--verbosez' ]
then
  SC_OPT=
  V=true
fi
$V && echo "Local rsync"

rsync -c --delete -r $NROOT/json_extra_staging/ $NROOT/json_extra/
rsync -c --delete -r $NROOT/json_staging/ $NROOT/json/

# upload
rsync -c --delete -r $NROOT/xmltv_staging/ $NROOT/xmltv/
tools/se-tvzon/nonametv-xmltv-gendatalist
rsync -c --delete -r $NROOT/xmltv/datalist.xml.gz $NROOT/datalist.xml.gz

$V && echo "chaeun"

rsync -c --delete -r $NROOT/xmltv/ chaeun:/server/xmltv_files/xmltv/
rsync -c --delete -r $NROOT/datalist.xml.gz chaeun:/server/xmltv_files/datalist.xml.gz

rsync -c --delete -r $NROOT/json_extra/ chaeun:/server/xmltv_files/json_extra/
rsync -c --delete -r $NROOT/json/ chaeun:/server/xmltv_files/json/

$V && echo "honeybee"

rsync -c --delete -r $NROOT/json_extra/ honeybee:/xmltv_files/json_extra/
rsync -c --delete -r $NROOT/json/ honeybee:/xmltv_files/json/
rsync -c --delete -r $NROOT/xmltv/ honeybee:/xmltv_files/xmltv/
rsync -c --delete -r $NROOT/datalist.xml.gz honeybee:/xmltv_files/datalist.xml.gz

$V && echo "compare"

# Compare
tools/se-tvzon/nonametv-xmltv-compare-run
rsync --delete -r /home/jnylen/content/xmltv_compare/ /var/www/html/compare/
