#!/bin/bash

NROOT=/content
PROOT=/home/jnylen/projects/nonametv

rm -rf $NROOT/xmltv_compare
mkdir $NROOT/xmltv_compare
cd $NROOT/xmltv_compare
$PROOT/tools/se-tvzon/nonametv-xmltv-compare $NROOT/staging/xmltv $NROOT/old/xmltv

rm -rf $NROOT/old/xmltv
mkdir $NROOT/old/xmltv
rsync -a $NROOT/staging/xmltv/ $NROOT/old/xmltv
