#!/usr/bin/perl -w

use strict;

use FindBin;
use lib "$FindBin::Bin/../lib";

use DateTime;
use File::Util;
use File::Copy qw/copy move/;
use File::Basename;
use File::Path qw/make_path/;

use NonameTV;
use NonameTV::DataStore;
use NonameTV::Config qw/ReadConfig/;
use NonameTV::Log qw/progress error d p w f/;

use Getopt::Long;

my $opt = { 'verbose' => 0 };

my $res = GetOptions( $opt, qw/verbose/ );

NonameTV::Log::SetVerbosity( $opt->{verbose} );

# Read configuration
my $conf = ReadConfig();
my $ds = NonameTV::DataStore->new( $conf->{DataStore} );
my $filestore = $conf->{FileStore};

# Channels
my %channel_data;
$channel_data{ "ams" } = "auto-motor-und-sport.tv";
$channel_data{ "bongusto" } = "bongusto.tv";
$channel_data{ "marcopolo" } = "marcopolo.de";

  # list files inside of the channel directory and check when they have been touched
  opendir(DIR, "/content/ftp/carusmedia/");
  foreach my $cff (readdir(DIR))
  {
    if($cff =~ /^\./) { next; }

    my ( $id, $pls, $date ) = split(/_/, $cff);

    my $cftype = join(',', File::Util->file_type( "/content/ftp/carusmedia/$cff" ) );
    if( $cftype !~ /PLAIN/ ){
      progress( "File $cff is $cftype - skipping" );
      next;
    }

    if( not exists( $channel_data{$id} ) )
    {
        print "Files with name $id hasnt been specified as a channel.\n";
        #unlink "/content/ftp/carusmedia/$cff";
    } else {
      make_path(dirname("$filestore/$channel_data{$id}/$cff"));
      move( "/content/ftp/carusmedia/$cff", "$filestore/$channel_data{$id}/$cff" );
      print "$cff moved to $channel_data{$id}\n";
    }

  }

exit;
