#!/bin/sh

NROOT=/content

# Xmltv
tools/nonametv-export Xmltv --export-channels
tools/nonametv-export Xmltv $1 $2 $3
tools/nonametv-export Xmltv --export-channels --channel-group TV
tools/nonametv-export Xmltv --export-channels --channel-group RADIO
tools/nonametv-export Xmltv --export-channels --channel-group DEV
tools/nonametv-export Xmltv --export-channels --channel-group Norway
tools/nonametv-export Xmltv --export-channels --channel-group Sweden
tools/nonametv-export Xmltv --export-channels --channel-group Finland
tools/nonametv-export Xmltv --export-channels --channel-group Denmark
tools/nonametv-export Xmltv --export-channels --channel-group Netherlands
tools/nonametv-export Xmltv --export-channels --channel-group Germany
tools/nonametv-export Xmltv --export-channels --channel-group Austria
tools/nonametv-export Xmltv --export-channels --channel-group Switzerland
tools/nonametv-export Xmltv --export-channels --channel-group Poland
tools/nonametv-export Xmltv --export-channels --channel-group Croatia
tools/nonametv-export Xmltv --export-channels --channel-group Hungary
tools/nonametv-export Xmltv --export-channels --channel-group Latvia
tools/nonametv-export Xmltv --export-channels --channel-group Lithuania
tools/nonametv-export Xmltv --export-channels --channel-group Estonia
tools/nonametv-export Xmltv --export-channels --channel-group Italy


# JSON
tools/nonametv-export Json --export-channels $1 $2 $3
tools/nonametv-export Json $1 $2 $3

tools/nonametv-export Json --export-channels --channel-group TV
tools/nonametv-export Json --export-channels --channel-group RADIO
tools/nonametv-export Json --export-channels --channel-group DEV
tools/nonametv-export Json --export-channels --channel-group Norway
tools/nonametv-export Json --export-channels --channel-group Sweden
tools/nonametv-export Json --export-channels --channel-group Finland
tools/nonametv-export Json --export-channels --channel-group Denmark
tools/nonametv-export Json --export-channels --channel-group Netherlands
tools/nonametv-export Json --export-channels --channel-group Germany
tools/nonametv-export Json --export-channels --channel-group Austria
tools/nonametv-export Json --export-channels --channel-group Switzerland
tools/nonametv-export Json --export-channels --channel-group Poland
tools/nonametv-export Json --export-channels --channel-group Croatia
tools/nonametv-export Json --export-channels --channel-group Hungary
tools/nonametv-export Json --export-channels --channel-group Latvia
tools/nonametv-export Json --export-channels --channel-group Lithuania
tools/nonametv-export Json --export-channels --channel-group Estonia
tools/nonametv-export Json --export-channels --channel-group Italy

# Honeybee-specific json
tools/nonametv-export Honeybee --export-channels $1 $2 $3
tools/nonametv-export Honeybee $1 $2 $3
