#!/usr/bin/perl -w

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib";

use Mail::Box;
use Mail::Box::Manager;
use MIME::Base64;

use File::Temp qw/tempdir/;
use File::Copy qw/move copy/;
use File::Basename;

use Getopt::Long;
use Digest::MD5;
use Data::Dumper;

use Encode qw/decode/;

use NonameTV;
use NonameTV::DataStore;
use NonameTV::Factory qw/CreateFileStore CreateDataStore/;
use NonameTV::Log qw/d p w f SetVerbosity StartLogSection EndLogSection/;

my $opt = { manual => 0,
            test => 0,
	    verbose => 0,
	    quiet => 0,
            };

my $res = GetOptions( $opt, qw/manual test verbose/ );

$opt->{verbose} = 1 if $opt->{manual};

SetVerbosity( $opt->{verbose}, $opt->{quiet} );

if( not $res ) {
  print << 'EOHELP';
 [--manual] [--test] [--verbose]

Extract files from mails in a maildir and store them using
NonameTV::FileStore.

  --manual  Ask the user which Importer to use if the information
            cannot be derived from the message.

  --test    Run the importer in test-mode.

EOHELP

  exit 1;
}

my $ds = CreateDataStore();

my $root = "/home/jnylen/maildir/.Projects/";
my @folders = qw(		 NonameTV-Data.MTV
                 		 NonameTV-Data.Mezzo
                 		 NonameTV-Data.HighTV
                 		 NonameTV-Data.EBS
                 		 NonameTV-Data.WildTV
                 		 NonameTV-Data.Euronews
                 		 NonameTV-Data.TV8Norge
                 		 NonameTV-Data.PokerChannel
                 		 NonameTV-Data.Gospel
		 NonameTV-Data.RTL2
		 NonameTV-Data.DWDE
		 NonameTV-Data.HaC
		 NonameTV-Data.ETVMedia
		 NonameTV-Data.VisjonNorge
		 NonameTV-Data.Disney
		 NonameTV-Data.Turner
		 NonameTV-Data.DMB
		 NonameTV-Data.PPS
		 NonameTV-Data.ServusTV
		 NonameTV-Data.DreiPlus
		 NonameTV-Data.Classica
		 NonameTV-Data.HopeChannel
		 NonameTV-Data.SSF
		 NonameTV-Data.Discovery
     NonameTV-Data.FightSports
        );

# Flag messages AFTER they have been processed. Then I normally
# only have to move the message to the correct folder.

my $tmpdir = tempdir( CLEANUP => 1 );

my $mgr = Mail::Box::Manager->new;

StartLogSection( "nonametv-parse-maildir", 0 );

foreach my $dir (@folders) {
  my $folder = $mgr->open( "$root.$dir",
                           access => 'rw',
                           extract => 'ALWAYS' );

  my $dir_pretty = $dir;
  $dir_pretty =~ s/NonameTV-Data\.//i;
  p "Running through $dir_pretty";

  foreach my $message ($folder->messages) {
    # Flag for delete
    if($message->label( 'flagged' )) {
        next; # Skip
    }
    #next unless $message->isMultipart;

    # Use Encode::MIME::Header
    my $subject = decode( 'MIME-Header', $message->get( 'Subject' ) ) || '';
    my $from = $message->get( 'From' );

    #d "Processing $from - $subject";

    if( process_parts( $message, $dir, $from, $subject ) ) {
      $message->label( 'flagged' => 1 );
      d "Processing succeeded.";
    }
    else {
      d "Processing failed.";
    }
  }
}

$mgr->closeAllFolders;

EndLogSection( "nonametv-parse-maildir" );

sub process_parts
{
  my( $part, $dir, $from, $subject ) = @_;

  my $type = $part->get('Content-Type');
#  return 0 if $type eq "text/plain";

  if($part->isMultipart)
  {
    my $count = 0;
    foreach my $child ($part->parts)
    {
      $count += process_parts( $child, $dir, $from, $subject );
    }
    return $count;
  }
  else
  {
    my $disp = $part->body->disposition;
    my $name = decode( 'MIME-Header',
		       $part->body->dispositionFilename ) || 'noname';
    my $size = $part->body->size;

    my $channel = guess_channel( $dir, $from, $subject, $name, $type, $size );

    if( (not defined $channel) and $opt->{manual} )
    {
      print "$name ($size bytes): ";
      $channel = <STDIN>;
      $channel =~ tr/\n\r //d;
      $channel = undef if $channel eq "";
    }

    if( not defined $channel ) {
      d "$name skipped.";
      return 0;
    }

    my $chd = $ds->sa->Lookup( 'channels', {xmltvid => $channel} );

    die "Unknown channel $channel" if not defined $chd;

    p "Adding file $name for $channel";

    my $fs = GetFileStore( $chd->{grabber} );
    my ($content);

    # Channels you only want it decoded, not fucked up
    #$channel eq "rtl2.de" or $channel eq "historytv.se" or
    #       $channel eq "historytv.no" or $channel eq "historytv.dk" or
    #       $channel eq "historytv.eu" or $channel eq "crimeandinvestigation.eu" or
    #       $channel eq "sonyentertainment.tv" or $channel eq "axntv.de" or $channel eq "animax.tv" or
    #       $channel eq "familytv.de" or $channel eq "dasneue.tv" or $channel eq "tnt-tv.dk
    if($name =~ /\.xml$/i) {
        $content = decode_base64($part->body);
    } else {
        $content = $part->decoded->string;
    }


    #print Dumper($content);
    $fs->AddFile( $channel, $name, \$content );
  }

  return $opt->{test} ? 0 : 1;
}

sub guess_channel
{
  my( $dir, $from, $subject, $filename, $type, $size ) = @_;

  if( $dir =~ /Disney/ ) {
    # The Disney filenames are very unreliable.
    if( $filename =~ /\bxd/i ) {
      return "xd.disneychannel.se";
    }
    if( $filename =~ /\bdxd/i ) {
      return "xd.disneychannel.se";
    }
    elsif( $filename =~ /playhouse/i ) {
      return "junior.disney.se";
    }
    elsif( $filename =~ /junior/i ) {
      return "junior.disney.se";
    }
    elsif( $filename =~ /disney\s*channel/i ) {
      return "disneychannel.se";
    }
    elsif( $filename eq "noname" ) {
      return undef;
    }
    elsif( $subject =~ /playhouse/i ) {
      return "junior.disney.se";
    }
    elsif( $subject =~ /junior/i ) {
      return "junior.disney.se";
    }
    elsif( $subject =~ /disney\s*channel/i ) {
      return "disneychannel.se";
    }

    return undef;
  }

 if( $dir =~ /Turner/ ) {
    # Word files
	return "cartoonnetwork.se" if $filename =~ /^cn\s*nordic\s+\(swe\)\s*\b/i;
	return "boomerangtv.se"    if $filename =~ /^boomerang\s*nordic\s*\(swe\)\s*\b/i;

	return "cartoonnetwork.no" if $filename =~ /^cn\s*nordic\s+\(nor\)\s*\b/i;
  return "boomerangtv.no"    if $filename =~ /^boomerang\s*nordic\s*\(nor\)\s*\b/i;

  return "cartoonnetwork.dk" if $filename =~ /^cn\s*nordic\s+\(dan\)\s*\b/i;
  return "boomerangtv.dk"    if $filename =~ /^boomerang\s*nordic\s*\(dan\)\s*\b/i;

  return "tcmeurope.com"     if $filename =~ /^tcm\s*nordic/i and $filename =~ /eng/i;
  return "se.tcmeurope.com"  if $filename =~ /^tcm\s*nordic/i and $filename =~ /swe/i;
  return "no.tcmeurope.com"  if $filename =~ /^tcm\s*nordic/i and $filename =~ /\(NOR\)/i and $filename !~ /dan/ and $filename !~ /\.xls$/i;
  return "dk.tcmeurope.com"  if $filename =~ /^tcm\s*nordic/i and $filename =~ /dan/i;

	# Excel (XLS)
	if( $filename =~ /\.xls$/i ) {
		# CNN
		if( $filename =~ /cnn/i ) {
		  return "cnn.com" if $filename =~ /\(in\s+cet\)/i;
		}

		# Cartoon network ENGLISH
    return "cartoonnetwork.com" if $filename =~ /^cn\s*nordic/i;
    return "cartoonnetwork.nl" if $filename =~ /^cn\s*dutch/i and $filename =~ /combo/i;
	}

  # XLS Nordic
  if( $filename =~ /\.(xls|xlsx)$/i ) {
	  return "tnt-tv.dk" if $filename =~ /^TNT/i and $filename =~ /DAN/i;
    return "tnt-tv.dk" if $filename =~ /^TNT/i and $filename =~ /DEN/i;
	  return "tnt-tv.se" if $filename =~ /^TNT/i and $filename =~ /SWE/i;
	  return "tnt-tv.no" if $filename =~ /^TNT/i and $filename =~ /NOR/i;
  }
 }

 if( $dir =~ /Euronews/ and $filename =~ /\.(xls|xlsx)/i ) {
    return "euronews.com";
 }

 if( $dir =~ /MTV/ ) {

    # excel (XLSX)
    if($filename =~ /\.xlsx$/i) {
    	return "classic.vh1.se" if $filename =~ /vh1.*euro.*classic/i;
    	return "classic.vh1.se" if $filename =~ /vh1euroclassic/i;

    	if($filename =~ /^mtv.*live/i) {
    	    return "hd.mtv.se" if $filename =~ /listings/i;
    	}
    }

    # excel (XLS)
    if($filename =~ /\.xls$/i) {
      return "classic.vh1.se" if $filename =~ /vh1.*euro.*classic/i;

      if($filename =~ /^mtv.*live/i) {
    	  return "hd.mtv.se" if $filename =~ /listings/i;
    	}
    }
 }

 if( $dir =~ /PokerChannel/ and $filename =~ /\.xlsx$/i ) {
     return "ginx.tv";
 }

 if( $dir =~ /Fatstone/ and $filename =~ /\.xlsx$/i ) {
  #   return "fatstone.tv";
 }

 if( $dir =~ /Mezzo/ ) {
    if($filename =~ /\.xls$/i) {
        return "hd.mezzo.tv" if $filename =~ /hd/i; # import mezzo live hd channel
        return "mezzo.tv" if $filename !~ /hd/i; # dont import mezzo live hd channel
    } elsif($filename =~ /\.xlsx$/i) {
        return "hd.mezzo.tv" if $filename =~ /hd/i; # import mezzo live hd channel
        return "mezzo.tv" if $filename !~ /hd/i; # dont import mezzo live hd channel
    }
 }

 if( $dir =~ /HighTV/ and $filename =~ /\.xls$/i ) {
     return "hightv.tv" if $filename =~ /epg/i;
 }

 if( $dir =~ /EBS/ and $filename =~ /\.xls$/i ) {
    # ENT. (BRIT) NORDIC
    return "bbcentertainment.com" if $filename =~ /brit\s+scandi/i;

    # Norway
    return "no.bbcentertainment.no" if $filename =~ /brit\s+norway/i;

    # ENT. (BRIT) EU
    return "bbcentertainment.eu" if $filename =~ /brit\s+europe/i;

    # HD
    return "bbchd.com" if $filename =~ /hd\s+scandi/i;
    return "bbchd.com" if $subject =~ /bbc\s+hd\s+scandi/i;

    # KNOW. (EARTH)
    return "bbcknowledge.com" if $filename =~ /knowledge\s+scandi/i;
    return "bbcknowledge.com" if $filename =~ /earth\s+scandi/i;

    # Lifestyle
    return "bbclifestyle.com" if $filename =~ /lifestyle\s+scandi/i;
 }

 if( $dir =~ /WildTV/ and $filename =~ /\.zip|.xml/i ) {
 	return "wildtv.ca";
 }

 if( $dir =~ /RTL2/ and $filename =~ /\.xml$/i ) {
  	return "rtl2.de"; # ÅÄÖ becomes ? in their mails.
 }

 if( $dir =~ /Gospel/ and $filename =~ /\.xls$/i ) {
   	return "gospel.tv";
 }

 if( $dir =~ /VisjonNorge/ and $filename =~ /\.xls$/i ) {
    return "visjonnorge.com";
 }

 if( $dir =~ /DWDE/ and $filename =~ /\.xls|.xlsx$/i ) {
    return "dw.de" if $filename =~ /Europa/i;
    return "asien.dw.de" if $filename =~ /Asien/i and $filename !~ /Afrika/i;
    return "english.dw.de" if $filename =~ /English/i;
    return "la.dw.de" if $filename =~ /Latino/i;
    return "amerika.dw.de" if $filename =~ /Amerika/i;
    return "asien.dw.de" if $filename =~ /Deutsch/i;
    return "dw.de" if $filename =~ /^DW\s+/i;
 }

 if( $dir =~ /HaC/ and $filename =~ /\.xml$/i ) {
     return "horseandcountry.tv";
 }

 if( $dir =~ /FightSports/ and $filename =~ /\.xls/i ) {
     return "fsf.fightsports.tv" if $filename =~ /FSF/i; # Nordics, France and Baltics
     #return "eu.fightsports.tv" if $filename =~ /eu/i; # Spain and EX Yugo
 }

 if( $dir =~ /ETVMedia/ ) {
    # Channel 1 Russia
    if( $filename =~ /\d{8}_\d{8}/i and $filename =~ /\.rtf$/i ) {
       return "1tvrus.com";
    }

    # TBN
    if( $filename =~ /TBN/i ) {
    #   return "tbn.org";
    }

    if( $subject =~ /WFC/i and $filename =~ /\.(xls|xlsx|txt)$/i ) {
    #    return "wfc.tv";
    }

    if( ( $subject =~ /fashiontv/i or $from =~ /\@ftv.com/i ) and $filename =~ /\.xlsx$/i ) {
        return "ftv.com" if $filename =~ /hotbird/i;
        return "hd.ftv.com" if $filename =~ /eurobird/i;
    }
 }

 if( $dir =~ /DMB/ ) {
    # Sony Entertainment TV, Gmbh.
    if($filename =~ /\.xml$/i or $filename =~ /\.xls$/i) {
        return "axntv.de" if $filename =~ /^AXN-/i;
        return "animax.tv" if $filename =~ /^AAX-/i;
        return "sonyentertainment.tv" if $filename =~ /^SEN-/i;
    }

    # ITV
    if($filename =~ /\.xml$/i) {
        return "familytv.de" if $filename =~ /^FamilyTV_/i;
    #    return "dasneue.tv" if $filename =~ /^DasNeueTV_/i;
        return "blizztv.de" if $filename =~ /^Blizz_/i;
    }
 }

 if( $dir =~ /PPS/ ) {
    return "disneychannel.de" if $filename =~ /\.(xml|zip)$/i;
 }

 if( $dir =~ /ServusTV/ and $filename =~ /\.xml$/i and $filename =~ /struppi/i ) {
    return "servustv.de" if $filename =~ /DE/i;
    return "servustv.com" if $filename !~ /DE/i;
 }

 if ( $dir =~ /OKGoteborg/ and $filename =~ /\.doc$/i ) {
  #  return "oppnakanalengoteborg.se";
 }

 if( $dir =~ /DreiPlus/ and $filename =~ /\.(zip|xml)$/i ) {
   return "3plus.tv" if $filename =~ /^dreiplus/i;
   return "4plus.tv" if $filename =~ /^vierplus/i;
   return "5plus.tv" if $filename =~ /^fuenfplus/i;
 }

 if( $dir =~ /Classica/ and $filename =~ /\.xlsx$/i ) {
 #  return "classica.de";
 }

 if( $dir =~ /HopeChannel/ and $filename =~ /\.xml$/i ) {
   return "hope-channel.de";
 }

 if( $dir =~ /SSF/ and $filename =~ /\.xlsx$/i ) {
   return "ssfmedia.ch";
 }

 if( $dir =~ /Discovery/ and $filename =~ /\.(xml|zip)$/i ) {
    return "dmax.discovery.de" if $filename =~ /^dmax/i;
    return "tlc.discovery.de" if $filename =~ /^tlc/i;
    return "animalplanet.discovery.de" if $filename =~ /^ap/i;
    #return "discovery.de" if $filename =~ /^dc/i;
 }

  return undef;
}

my $filestores = {};

sub GetFileStore {
  my( $importer ) = @_;

  if( not defined $filestores->{$importer} ) {
    $filestores->{$importer} = CreateFileStore( $importer );
  }

  return $filestores->{$importer}
}

sub md5sum {
  my( $file ) = @_;
  open(FILE, $file) or die "Can't open '$file': $!";
  binmode(FILE);

  return Digest::MD5->new->addfile(*FILE)->hexdigest;
}
