#!/bin/bash

NROOT=/home/jnylen/content
PROOT=/home/jnylen/projects/nonametv/

#Q="--quiet --quiet"
Q="--verbose"
F="--force-update"

h=true
d=true
one=true

cd $PROOT

if [ $1x = --weeklyx ]
then
  # Run weekly commands.
  perl -I lib tools/nonametv-remove-old
  tools/se-tvzon/nonametv-import-allhttp --remove-old

  # Move away old files  after 6 weeks
  tools/nonametv-filestore-moveold --all --leavedays 42

  # Remove old files after 70 days (safes space)
  tools/nonametv-filestore-removeold --all --leavedays 70

  # remove Tvrage cache (they can't be updated automatic..
  # .. as tvrage doesnt provide that sort of system)
  rm /nonametv/contentcache/Tvrage/tvrage.db

  # Make sure we have all xmltv updated. As some seem to go missing (Somehow)
  # (for example if the time on the server is way off)
  #tools/nonametv-export Xmltv --force-export
  tools/nonametv-export Json --force-export

  # Remove old programmes and batches - dont use, fucks up the previouslyshown
  # augmenter
  #perl -I lib tools/nonametv-remove-old

  # Generate the docs for the importers etc
  tools/nonametv-generate-doc /home/jnylen/content/docs/

  exit
fi

if [ $1x = --dailyx ]
then
  # Run daily commands
  d=
fi

if [ $1x = --onex ]
then
  # Run 13.00 commands
  one=
fi

if [ $1x = --hourlyx ]
then
  # Run hourly commands
  h=
fi

# Update tvdb
$d perl -I lib tools/nonametv-update-tvdb sv
$d perl -I lib tools/nonametv-update-tvdb en
$d perl -I lib tools/nonametv-update-tvdb de
$d perl -I lib tools/nonametv-update-tvdb no
$d perl -I lib tools/nonametv-update-tvdb fi
$d perl -I lib tools/nonametv-update-tvdb da
$d perl -I lib tools/nonametv-update-tvdb hr
$d perl -I lib tools/nonametv-update-tvdb it
$d perl -I lib tools/nonametv-update-tvdb nl
$d perl -I lib tools/nonametv-update-tvdb fr

# Import files sent through ftp
$d tools/se-tvzon/nonametv-filestore-svt $Q
$d tools/se-tvzon/nonametv-filestore-venetsia $Q
$d tools/se-tvzon/nonametv-filestore-prosieben $Q
$d tools/se-tvzon/nonametv-filestore-tele5 $Q
$d tools/se-tvzon/nonametv-filestore-carusmedia $Q

# Ruby importers for files
$d ruby ftv_importer.rb
$d ruby tv5_importer.rb

# Import everything
$d tools/se-tvzon/nonametv-import-allhttp $Q
$h tools/se-tvzon/nonametv-import-allhttp $Q --short-grab
tools/se-tvzon/nonametv-import-allmail $Q

# Remove old
$d perl -I lib/ tools/nonametv-export Xmltv --remove-old
$d perl -I lib/ tools/nonametv-export Json_extra --remove-old
$d perl -I lib/ tools/nonametv-export Json --remove-old
$d tools/nonametv-icon-update --quiet --unattended

# Update the Combiner-channels as well.
$d perl -I lib tools/nonametv-import Combiner $Q
$h perl -I lib tools/nonametv-import Combiner --short-grab $Q

# Update the Downconverter-channels as well.
$d perl -I lib tools/nonametv-import Downconverter $Q
$h perl -I lib tools/nonametv-import Downconverter --short-grab $Q

# Batchlog
$d perl -I lib tools/nonametv-batchlog > $NROOT/html/00status.html

# Export
$d tools/se-tvzon/nonametv-updatesite $Q

# Upload to www (daily)
$d tools/se-tvzon/nonametv-upload $Q

# Run after, everything
$d rsync --delete -r /home/jnylen/content/html/00status.html /var/www/xmltv/

# Combined files
$d ruby /home/jnylen/notice.rb
$d /home/jnylen/xmltv-grabber
